### ISSUE TITLE
paperqa的数据量级的问题

### ISSUE THREAD

**Issue by randomtutu** [RUCAIBox/BAMBOO#3]
求问，paperqa的数据，文章里面写的是40/40，但是json文件里有100/100的case，这个是有重复或者其他原因吗

**Comment by randomtutu** [comment]
作者你好，你们的有部分数据可能存在一些问题。

在meeting qa里面，第93个case，参考答案是一个空串。

其余的文件里可能还存在，可以检查一下。

**Comment by 1190303125** [comment]
感谢您的发现，我们对少数存在问题的数据进行了更新。
